<?php

define('BASE_NAMESPACE', 'bc');

/**
 * Implements hook_permission().
 */
function bc_islandora_permission() {
  return array(
    'administer bc_islandora' => array(
      'title' => t('Administer Barnard Islandora'),
      'description' => t('Perform administrative tasks for Barnard Islandora.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bc_islandora_menu() {
  return array(
    'view/%' => array(
      'page callback' => 'bc_islandora_page_view',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
    ),
    'download_datastream/%/%' => array(
      'page callback' => 'bc_islandora_download_datastream',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
    ),
    'admin/islandora/bc_config' => array(
      'page callback' => 'drupal_get_form',
      'title' => 'Configure Barnard Islandora',
      'type' => MENU_NORMAL_ITEM,
      'page arguments' => array('bc_islandora_config'),
      'access arguments' => array('administer bc_islandora'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function bc_islandora_theme($existing, $type, $theme, $path) {
  return array(
    'bc_islandora_object' => array(
      'variables' => array(
        'pid' => NULL,
        'title' => NULL,
        'paged' => FALSE,
        'start_page' => NULL,
      ),
      'file' => 'includes/bc_islandora.theme.inc',
    ),
    'bc_islandora_exhibit' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'file' => 'includes/bc_islandora.theme.inc',
    ),
  );
}

function bc_islandora_page_view($pid) {
  return theme('bc_islandora_object', array('pid' => BASE_NAMESPACE . ':' . $pid));
}

function bc_islandora_download_datastream($pid, $dsid) {
  module_load_include('inc', 'islandora', 'includes/datastream');

  $mods = _bc_islandora_mods_object($pid);
  $xml = $mods['mods'];
  if ($id  = (string) $xml->identifier) {
    $object[$dsid]->label = $id;
    //bc_islandora_view_datastream($object[$dsid]);
    islandora_view_datastream($object[$dsid], TRUE);
  }
  else {
    return drupal_not_found();
  }
}

function bc_islandora_config($form, &$form_state) {
  $form['bc_islandora_namespace'] = array(
    '#type' => 'textfield',
    '#title' => t('Base namespace'),
    '#required' => TRUE,
    '#default_value' => variable_get('bc_islandora_namespace', BASE_NAMESPACE),
  );
  $form['bc_islandora_collection_newspaper'] = array(
    '#type' => 'textfield',
    '#title' => t('Newspaper collection pid'),
    '#default_value' => variable_get('bc_islandora_newspaper_pid', ''),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

function bc_islandora_config_submit($form, &$form_state) {
  variable_set('bc_islandora_namespace', $form_state['values']['bc_islandora_namespace']);
  variable_set('bc_islandora_newspaper_pid', $form_state['values']['bc_islandora_collection_newspaper']);
  $form_state['redirect'] = 'admin/islandora/bc_config';
  drupal_set_message(t('Saved changes.'));
}

/**
 * Implements hook_block_info().
 */
function bc_islandora_block_info() {
  $blocks = array(
    'bc_islandora_newspaper' => array(
      'info' => t('Newspaper Collection'),
      'status' => BLOCK_VISIBILITY_LISTED,
      'pages' => array('bulletin'),
      'region' => 'content',
    ),
    'bc_islandora_yearbook' => array(
      'info' => t('Book Collection'),
      'status' => BLOCK_VISIBILITY_LISTED,
      'pages' => array('yearbook'),
      'region' => 'content',
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_save().
 */
function bc_islandora_block_save($delta = '') {
  if (preg_match('/^bc_islandora_/', $delta) !== FALSE) {
    $variable = $delta . '_pid';
    variable_set($variable, $edit['islandora_collection_pid']);
  }
}

/**
 * Implements hook_block_view().
 */
function bc_islandora_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'bc_islandora_newspaper':
      if ($collection_pid = variable_get($delta . '_pid', 'islandora:1')) {
        module_load_include('inc', 'islandora_newspaper', 'includes/utilities');
        $years_output = '<div class="years">';
        $months_output = '<div class="months">';
        $issues_output = '<div class="issues">';
        $months_sort = array();
        $issues_sort = array();

        $paper = islandora_object_load($collection_pid);
        $issues = islandora_newspaper_get_issues($paper);
        $grouped_issues = islandora_newspaper_group_issues($issues);
        $years_output .= '<ul class="years">';
        foreach ($grouped_issues as $year => $months) {
          $years_output .= '<li class="year" id="' . $year . '"><a href="#">' . $year . '</a></li>';

          foreach ($months as $month => $issues) {
            $month_display = date('F', strtotime($year . '-' . $month));
            $months_sort[$year][$month] = '<li class="month" id="' . $month . '"><a href="#">' . $month_display . '</a></li>';
            foreach ($issues as $day => $issue) {
              $issue_url = 'view/' . str_replace(BASE_NAMESPACE . ':', '', $issue[0]['pid']);
              $issues_sort[$month][$day] = '<li class="issue">' . l(preg_replace('/^0/', '', $day), $issue_url) . '</li>';
            }
          }
        }

        $years_output .= '</ul></div>';
        foreach ($months_sort as $year => $month) {
          ksort($month);
          $months_output .= '<ul class="months-' . $year . '">';
          $months_output .= implode("\n", $month);
          $months_output .= '</ul>';
          foreach ($issues_sort as $issue_month => $day) {
            ksort($day);
            $issues_output .= '<ul class="issues-' . $year . '-' . $issue_month . '">';
            $issues_output .= implode("\n", $day);
            $issues_output .= '</ul>';
          }
        }

        $months_output .= '</div>';
        $issues_output .= '</div>';

        $output = '<div class="bulletin-nav">
            <span class="browse">Browse</span><span class="month"></span><span class="day"></span><span class="year"><a id="nav" href="#"></a></span>
          </div>';
        $output .= '<div class="bulletin-calendar">' . $years_output . $months_output . $issues_output . '</div>';
        $block['content'] = $output;
      }
    break;
    // TODO
    case 'bc_islandora_yearbook':
      if ($collection_pid = variable_get($delta . '_pid', 'islandora:bookCollection')) {
        $output = '<div id="yearbook-nav">';
        $book_collection = islandora_object_load($collection_pid);
        $query = <<<EOQ
PREFIX islandora-rels-ext: <http://islandora.ca/ontology/relsext#>
PREFIX fedora-rels-ext: <info:fedora/fedora-system:def/relations-external#>
SELECT ?object
FROM <#ri>
WHERE {
  ?object fedora-rels-ext:isMemberOf <info:fedora/{$collection_pid}> ;
       <fedora-model:hasModel> <info:fedora/islandora:bookCModel> ;
}
EOQ;
        $results = $book_collection->repository->ri->sparqlQuery($query);
        foreach ($results as $r) {
          $pid = $r['object']['value'];
          $year = array_pop(explode('-', $pid));
          $output .= '<span class="year">' . l($year, 'view/' . str_replace(BASE_NAMESPACE . ':', '', $pid)) . '</span>';
        }
        $output .= '</div>';
        $block['content'] = $output;
      }
    break;
  }
  return $block;
}

function bc_islandora_preprocess_islandora_solr(&$variables) {
  foreach ($variables['results'] as $i => $r) {
    $variables['results'][$i]['object_url'] = str_replace('islandora/object/', 'view/', str_replace('bc:', '', $r['object_url']));
  }
}

function _bc_islandora_solr_query($fq) {
  $qp = new IslandoraSolrQueryProcessor();
  $qp->buildAndExecuteQuery('', array('f' => $fq));
  return $qp->islandoraSolrResult;
}

function _bc_islandora_mods_object($pid) {
  if ($object = islandora_object_load($pid)) {
    return array(
      'object' => $object,
      'mods' => simplexml_load_string($object['MODS']->getContent(NULL))
    );
  }
}
